### ISSUE TITLE
Plant Tycoon Cog

### ISSUE THREAD

**Issue by SnappyDragon18** [SnappyDragon18/Snap-ons#1]
PT cog is the advanced version of its prototype, plants.py cog. Here are the planned features:
>Seed packs (cost $1000 and contain 5 seeds)
>Watering and Fertilizing plants
>Variable growth times for different plants
>More Plants
>Plants when fully grown reward you with money

**Comment by Chovin** [comment]
Discussion from Discord
> * various regular plants as well as mythical / plants from games, movies, etc.
* plants die if you don't take care of them - water them but not too much
* encrypt the plant data so you have to plant them in order to figure out what they are and what they grow into
* you have to buy seeds, can't plant too many at a time
* plants have chances to turn into other things or such ex. bag of bells (animal crossing) has a possibility of turning into a golden tree which gives you back a bunch of economy
* some plants grow very fast. rarer plants are harder to take care of and take a long time to grow.
* how long do plants last after being fully grown? do you have a garden of a fixed size that you can keep plants in? buying new pots to be able to plant more?

**Comment by SnappyDragon18** [comment]
Changelog:
>Added Watering and Fertilizing

**Comment by SnappyDragon18** [comment]
Changelog:
>Different Plant rarities have different payouts and growth times
>Each ``[p]grow`` costs 100$
>A total of 40 plants, fictional and real

**Comment by SnappyDragon18** [comment]
Plants v3.0- Gardening is out.
Paddo and I working on it.
To do list:
Fix fertilizing.
Add pruning.

**Comment by SnappyDragon18** [comment]
Fixed fertilizing and added pruning. Next thing to add is diseases.
